### ISSUE TITLE
Release a new version onto the PuppetForge

### ISSUE THREAD

**Issue by tombuildsstuff** [genebean/genebean-zabbixagent#3]
Hey - are there any plans to release a new version of this module onto the PuppetForge? Right now the latest version on the forge is 2.3.0, and the latest tag in git in 2.4.1 - just wondering if I need to use the URL rather than the Forge version?

Thanks!

**Comment by genebean** [comment]
Sorry I didn't message you back when I released v2.5.0 on 8/15 but I wanted to be sure to let you know that v2.6.0 is now on the forge.

**Comment by tombuildsstuff** [comment]
@genebean great - thanks!
